version: '3.4'

services:
  postgres:
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DeliveryServiceDb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword


  deliveryservice.api:
    image: ${DOCKER_REGISTRY-}deliveryserviceapi
    build:
      context: .
      dockerfile: DeliveryService_ASP.NET/Dockerfile
    ports:
      - 5000:80
    depends_on:
     - rabbitmq

  deliveryservice.services.paymentapi:
    image: ${DOCKER_REGISTRY-}deliveryserviceservicespaymentapi
    build:
      context: .
      dockerfile: DeliveryService.Services.PaymentAPI/Dockerfile
    ports:
      - 5001:80
    depends_on:
     - rabbitmq

  deliveryservice.services.productapi:
    image: ${DOCKER_REGISTRY-}deliveryserviceservicesproductapi
    build:
      context: .
      dockerfile: DeliveryService.Services.ProductAPI/Dockerfile
    ports:
      - 5002:80
    depends_on:
     - rabbitmq

  deliveryservice.services.restaurantapi:
    image: ${DOCKER_REGISTRY-}deliveryserviceservicesrestaurantapi
    build:
      context: .
      dockerfile: Services/RestaurantAPI/DeliveryService.Services.RestaurantAPI/Dockerfile
    ports:
      - 5003:80
    depends_on:
     - rabbitmq

  deliveryservice.services.orderapi:
    image: ${DOCKER_REGISTRY-}deliveryserviceservicesorderapi
    build:
      context: .
      dockerfile: Services/OrderAPI/DeliveryService.Services.OrderAPI/Dockerfile
    ports:
      - 5004:80
    depends_on:
     - rabbitmq


  # emailservice:
  #   image: hiddenviki/emailservice2-app:latest-amd642-another-one
  #   ports:
  #     - 8080:80

  deliveryservice.services.courierapi:
    image: ${DOCKER_REGISTRY-}deliveryserviceservicescourierapi
    build:
      context: .
      dockerfile: Services/CourierAPI/DeliveryService.Services.CourierAPI/Dockerfile
    ports:
      - 5005:80
    depends_on:
     - rabbitmq

  deliveryservice.authapi:
    image: ${DOCKER_REGISTRY-}deliveryserviceauthapi
    build:
      context: .
      dockerfile: Services/AuthAPI/DeliveryService.AuthAPI/Dockerfile
    ports:
      - 5006:80
    depends_on:
     - rabbitmq

volumes:
  postgres-data:



  







