version: '3.4'

services:
  postgres:
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DeliveryServiceDb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped


  deliveryservice.api:
    image: ${DOCKER_REGISTRY-}deliveryserviceapi
    build:
      context: .
      dockerfile: DeliveryService_ASP.NET/Dockerfile
    ports:
      - 5000:80

  deliveryservice.services.paymentapi:
    image: ${DOCKER_REGISTRY-}deliveryserviceservicespaymentapi
    build:
      context: .
      dockerfile: DeliveryService.Services.PaymentAPI/Dockerfile
    ports:
      - 5001:80

  deliveryservice.services.productapi:
    image: ${DOCKER_REGISTRY-}deliveryserviceservicesproductapi
    build:
      context: .
      dockerfile: DeliveryService.Services.ProductAPI/Dockerfile
    ports:
      - 5002:80


  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  postgres-data:



  



