version: '3.4'

services:
  deliveryservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  deliveryservice.services.paymentapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

