version: '3.4'

services:
  deliveryservice.api:
    image: ${DOCKER_REGISTRY-}deliveryserviceapi
    build:
      context: .
      dockerfile: DeliveryService_ASP.NET/Dockerfile
    ports:
      - 5000:80
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2021-09-15T04-54-25Z.hotfix.908b0f10a
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data
    volumes:
      - ./docker/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    
